FROM golang:1.21-alpine as builder

WORKDIR /src

COPY main.go .
COPY go.mod .

RUN go build \
    -ldflags "-s -w" \
    -o build/main \
    main.go

FROM scratch

COPY --from=builder /src/build/main /main
CMD ["/main"]